name: GitHub Metrics

on:
  # Update once a day
  schedule: [{cron: "0 0 * * *"}]
  # Or update manually from Actions tab
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Replace with your username
          token: ${{ secrets.METRICS_TOKEN }}
          user: 04AR
          template: classic
          base: header, activity, community, repositories
          config_timezone: Asia/Kolkata

          # ğŸ“… Isometric commit calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # ğŸˆ·ï¸ Languages activity (by commits)
          plugin_languages: yes
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: commit
